### ISSUE TITLE
Ask CLI error deploying new unedited project

### ISSUE THREAD

**Issue by jmeyers91** [alexa/alexa-skills-kit-sdk-for-nodejs#529] opened 2019-03-19 20:25 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Just got back to work on an Alexa skill I hadn't touched in a few months, but it wouldn't deploy, so I created a 'hello world' project with the ASK CLI and tried to deploy it, but got the same error:

```
[Error]: Get Lambda ARN ask-custom-skill-sample-nodejs-hello-world-default failure for custom/default.
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type string, TypedArray, or DataView. Received type undefined
```

## Expected Behavior
Should deploy successfully.

## Current Behavior
Throws an error and doesn't deploy.

## Steps to Reproduce (for bugs)
```
npm install -g ask-cli
ask new # Select node, hello world, leave name default
cd skill-sample-nodejs-hello-world
ask deploy
```

## Your Environment

* ask v1.6.4
* OSX Mojave 10.14.2

## Node.js and NPM Info
* Node.js version used for development: v10.11.0
* NPM version used for development: v6.4.1

**Comment by RonWang** [comment] 2019-03-26 04:48
Hey @jmeyers91 ,

Thanks for the post! I tried to reproduce this issue, but the skill template works correct for me. Because this error message is from AWS Lambda client when you attempted to retrieve the Lambda function, could you check if you AWS credential is set correctly? Could you check if your ~/.aws/credentials file is same format as mentioned in https://docs.aws.amazon.com/ses/latest/DeveloperGuide/create-shared-credentials-file.html?

Thanks,
Ron

**Comment by RonWang** [comment] 2019-04-08 21:17
Closing this issue. Please feel free to reopen if you have further question!

**Closed as completed by RonWang** 2019-04-08 21:17 UTC
Labels: cli

**Comment by jmeyers91** [comment] 2019-04-08 22:48
Sorry didn't get around to responding about this. Updating the ASK CLI to `1.6.5` seems to have fixed this issue, but I'm still running into some AWS credential issues. My `~/.aws/credentials` file looks like this:

```
[default]
aws_access_key_id=AKIBJQTRxxxxxxx
aws_secret_access_key=fG0A6MS2R9V1Oxxxwxxxxxxxxxxxxx
```

My `~/.zshrc` includes the same credentials as env variables:

```
export AWS_ACCESS_KEY_ID=AKIBJQTRxxxxxxx
export AWS_SECRET_ACCESS_KEY=fG0A6MS2R9V1Oxxxwxxxxxxxxxxxxx
```

I can also echo these env variable credentials:

```bash
echo $AWS_ACCESS_KEY_ID
AKIBJQTRxxxxxxx
```

And I'm guessing the ask CLI doesn't load them, but I have the same credentials in a `.env` file in the project I'm working. Currently the only way I can deploy with the ASK CLI is by defining the AWS credentials in the command:

```bash
AWS_ACCESS_KEY_ID=AKIBJQTRxxxxxxx AWS_SECRET_ACCESS_KEY=fG0A6MS2R9V1Oxxxwxxxxxxxxxxxxx ask deploy
```

I'm going to leave this ticket closed since I'm no longer working on that project, and it seems like I'm the only one running into this issue. It's probably some issue with my local setup, but I can't see any reason the AWS CLI wouldn't pickup any of the credentials I've defined (my custom scripts that use `aws-sdk` to load from the env work fine).
