### ISSUE TITLE
Slot Validations with Manual Dialog Delegation Doesn't Work

### ISSUE THREAD

**Issue by TheDreamSaver** [alexa/alexa-skills-kit-sdk-for-nodejs#539] opened 2019-04-11 13:54 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Slot Validations with Manual Dialog Delegation Doesn't Work

## Expected Behavior
1. I have an intent with three slots, all required.
2. All slots have slot validations set as well.
3. Dialog Delegation is disabled and in manual mode.
4. In the code when I'm getting the dialog.state = "Started" request, I'm actually setting the second slot value to something based on a condition.

5. So now my expected behavior is when dialog delegation starts it should already fill that slot and only prompt for slot no. 1 and 3.

## Current Behavior
6. But what is happening is, skill prompts for slot 1. I respond with value. 
And now instead of prompting for slot 3 it is giving me error - which is speaking, the validation prompt for slot 2.

At the same time, the json though shows both slot 1 & slot 2 filled.

## Possible Solution
It works as expected when I don't use slot validations in the console, but if I add validations for the second slot and also set it on start like in step 4, it behaves weirdly.

Instead of prompting for slot 3rd after getting slot 1st value, it speaks out the validation prompt of slot second.

## Steps to Reproduce (for bugs)
Create an intent with three slot values, all of them required, also add slot validations to them. Now disable auto delegation and handle Dialog.state = "started" in your code.
In Dialog.state = "started" fill the second slot value manually and test the intent.

## Context
I am trying to minimize the no of questions Alexa asks based on prior input, in order to decrease friction. I am making it required and validations are needed because for the first time user needs to input that accordingly.

## Your Environment

* ASK SDK for Node.js used: ^2.1.0-beta.1
* Operating System and version: Windows 10 + Ubuntu 18.04 bionic [Ubuntu on Windows 10]

## Node.js and NPM Info
* Node.js version used for development: Runtime 8.10 Local (v9.11.2)
* NPM version used for development: 6.4.1

**Comment by TheDreamSaver** [comment] 2019-04-12 11:21
Update - This issue has been observed when I use custom slots and the "Accept only Slot Type's values and synonyms" validation, but works well in case of built-in slot and accept only/reject only a set of values.

**Comment by ShenChen93** [comment] 2019-05-09 23:58
Hi @TheDreamSaver 

Sorry for reponding late and thanks for posting this issue. We do observed this problem, although slot value is set to a correct value manually, the validation will be invoked. This is not caused by SDK, I have reached out to internal service team.  Will notice you once we got their reply. 

Thanks,
Shen

**Comment by harristom** [comment] 2019-06-02 13:07
I'm having the same problem, is there any news on this?

**Comment by ShenChen93** [comment] 2019-06-07 22:14
@harristom  The teams are currently looking into this. I will update the thread once we receive some info.

**Comment by ShenChen93** [comment] 2019-06-19 20:25
@TheDreamSaver @harristom 

Thanks for your patient. The service team's reply is the validation will always be triggered if slot validation is enabled. Similar issue is reported in python sdk https://github.com/alexa/alexa-skills-kit-sdk-for-python/issues/85.  The service team is looking for more information from the developers regarding this. It would be great if you can vote for this feature [here](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote/suggestions/37895404-enable-custom-slot-validation-for-multi-turn-dialo).

Thanks,
Shen

**Closed as completed by ShenChen93** 2019-06-19 20:25 UTC
Labels: dialog management
