### ISSUE TITLE
Stateless handlers no longer work

### ISSUE THREAD

**Issue by coltonw** [alexa/alexa-skills-kit-sdk-for-nodejs#196] opened 2017-10-08 18:29 UTC
Previously, if you didn't add the `Alexa.CreateStateHandler` around your intents, those intents could be called from any state.  This is used in the [high low game example](https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/src/index.js) for instance as `guessAttemptHandlers`.

With no code change on my end, it seems like all the stateless handlers no longer get called.  Is this intentional?  Is anyone else seeing this behavior?

**Comment by brendanclement** [comment] 2017-10-12 04:46
I gave this a shot and I'm not able to reproduce this behaviour.  Testing out the high/low game yields the correct result on both Node 6.10 and 4.3 

Are you calling the stateless handler like: `this.emit('handlerToCall')` ?  Are you able to reproduce this same behaviour on the high/low guess game?

**Comment by coltonw** [comment] 2017-10-15 21:01
Hmm, no idea how this is happening then...  I am doing exactly `this.emit('handerToCall')`

I am on node 8, but that shouldn't matter I would think?  I am not super worried about this since I just worked around it by adding the stateless functions to all my states.  Feel free to close.

**Comment by brendanclement** [comment] 2017-10-15 22:04
Out of curiosity I just gave it a shot on node v8.7 and got the same behaviour as v4 and v6.
I'm certain the node version doesn't matter here. Is there an error thrown on your side when you try to call `this.emit('handlerToCall')` ?

**Comment by coltonw** [comment] 2017-10-15 22:39
It calls the Unhandled intent in the state I am in.

**Comment by Amazon-tianrenz** [comment] 2017-10-31 18:57
I'm closing this as the issue described can not be reproduced. Please feel free to reopen this if further problems occur

**Closed by Amazon-tianrenz** 2017-10-31 18:57 UTC
