### ISSUE TITLE
addRequestHandlers array of requests - Feature Request

### ISSUE THREAD

**Issue by reflexdemon** [alexa/alexa-skills-kit-sdk-for-nodejs#504] opened 2019-01-17 21:11 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I have reviewed #383  and I am trying to achevie something else.

## Expected Behavior
 I have actually extrnalized all my implementations outside of index.js as the file size was growing very fast. SoI have something like this now.

```
const customHandlers = [
            './handlers/LaunchRequest.handler',
            './handlers/pointBalanceIntent.handler',
            './handlers/HelpIntentHandler.handler',
            './handlers/CancelAndStopIntentHandler.handler',
            './handlers/endIntent.handler',
            './handlers/popularProductIntent.handler',
            './handlers/getCartProductsIntent.handler',
            './handlers/getWishListProductsIntent.handler',
            './handlers/getRecentOrders.handler',
            './handlers/getAllCategoriesIntent.handler',
            './handlers/getTopProductsByCategoryIntent.handler',
            './handlers/specificProductIntent.handler'
];
const customHandlerInstance = _.map(customHandlers, (hdr) => require(hdr));
```
I try to add the handlers like below
```
exports.handler = skillBuilder
  .addRequestHandlers(
    ...customHandlerInstance //destructure
  )
  .addErrorHandlers(ErrorHandler)
  .lambda();
```

## Current Behavior
This throws error while deploying the lambdas.

## Possible Solution
To be able to just add a specific folder where the handlers are coded and the addRquestHandlers adds them back.

## Steps to Reproduce (for bugs)
I have provided sample above.

## Context
This is requiring me to make multiple entries to add a new handler.

## Your Environment
```
Operating System: macOS 10.13.6
❯ node -v
v8.11.2
❯ npm -v
6.4.1
❯ ask -version
1.5.3
```

**Comment by tianrenz** [comment] 2019-01-17 23:28
HI @reflexdemon , 

Thanks for the interesting input here. I'll bring the idea back to the team and discuss the feature. 

Meanwhile, the code snippet you posted above should be able to work. Could you paste the error log here?

Regards

**Comment by reflexdemon** [comment] 2019-01-18 20:43
@tianrenz Thanks for quick turnaround. I got that working on the hello world program. Now,I need to do investigation on why it will not work on my main project.

I have done the following improvements to the sample hello-world code.
1. Moved al the handlers to individual files.
2. Have ability to include new handlers as and when needed to the `./handlers` folder and this gets registered automatically.

If anyone is intrested in looking at a working sample, please look into the below project.
https://github.com/reflexdemon/skill-sample-nodejs-hello-world


At this mement, we can call this issue is resolved.

**Comment by tianrenz** [comment] 2019-01-18 20:44
Hi @reflexdemon , 

Glad the problem is solved! Closing the issue now. Please feel free to reopen if need any further help!

Regards

**Closed as completed by tianrenz** 2019-01-18 20:44 UTC
