### ISSUE TITLE
Documentation wrong alexa.appId = appId;

### ISSUE THREAD

**Issue by pursual** [alexa/alexa-skills-kit-sdk-for-nodejs#150] opened 2017-07-11 22:01 UTC
`alexa.appId = appId;` has slowly stopped working on a number of my skills. Apparently the correct format is: `alexa.APP_ID = appId;`

The old format used to work, and is widely quoted on the web, but is no longer reliable. 
https://medium.com/@sadranyi/errormessage-invalid-applicationid-amzn1-ask-skill-xxxxxxx-7cefd8478d17

**Comment by ryhinchey** [comment] 2017-07-13 18:11
I can confirm this as well. I created a PR to update the Readme

**Comment by gadgetchnnel** [comment] 2017-07-17 19:45
Looking at the code in the library, it still has the property as **appId** and not **APP_ID**. I think what you are seeing is issue #147 where the Service Simulator is sending the wrong application id (sending the string "applicationId") and breaking verification, this has been reported over at the developer forums and Amazon are aware of it.
I think this reason why switching back to APP_ID is working for you is because this is effectively disabling verification of the application id, as alexa.appId is then undefined.

**Comment by pursual** [comment] 2017-07-17 19:48
The skill actually stopped working on devices, until the appId check was removed. It had previously worked. I'm not sure what is going on.

**Comment by jeffreyisham** [comment] 2017-07-22 14:50
My app gives an application id warning when I use APP_ID and appId generates a build error.

**Comment by OezlemYi** [comment] 2017-10-29 16:47
alexa.applicationId = '' worked for me

**Comment by Amazon-tianrenz** [comment] 2017-10-31 19:39
Hi, 
Current SDK has remove the appId check for cases when appId is not assigned value and instead throw a warning in the console. 
I'm closing this for now. Please feel free to reopen if issue persists.

**Closed by Amazon-tianrenz** 2017-10-31 19:39 UTC

**Comment by MickL** [comment] 2018-01-31 14:51
`alexa.appId`, as described in the readme, is not working. Lambda says "Invalid ApplicationId". Changing it to `APP_ID` works. Please update the readme @Amazon-tianrenz

**Comment by kitingChris** [comment] 2018-03-07 12:58
Would be good to know how it is done correctly? 
In the lambda config I set the skillID. How can I access and use it in my code without hardcoding it? 
Would be really nice to know @Amazon-tianrenz

**Comment by Amazon-tianrenz** [comment] 2018-03-07 17:49
The skillId configuration in lambda console works exactly the same as the APP_ID check in the SDK. You won’t need to configure both. They all check if the value supplied matches with what the event json has(which means the lambda is invoked through Alexa skills kit service )

**Comment by kitingChris** [comment] 2018-03-08 08:43
@Amazon-tianrenz using the APP_ID variable did not work with the latest sdk. Got an error using that. 

Leaving it empty works but produces warnings.

But I discovered I could use it like this:
```
alexa.appId = event.session.application.applicationId;
```

But still unsure how it is intended to be used correctly.
