### ISSUE TITLE
Kindle Fire flash card doesn't show link account link

### ISSUE THREAD

**Issue by LazyDave76** [alexa/alexa-skills-kit-sdk-for-nodejs#131] opened 2017-06-12 08:06 UTC
When using Alexa on kindle fire 7 you are presented with some UI with the response when using the 'WithLinkAccountCard' response.   (I'm not sure what these are called, so I've attached an image to help explain).

The hyperlink to link the account is not shown in these cards.  These are not the card inside the Alexa app, they still work perfectly.

![image](https://user-images.githubusercontent.com/5232115/27023518-c86a3646-4f4a-11e7-8947-5a55774a5176.png)

**Comment by Amazon-tianrenz** [comment] 2017-11-01 23:39
Hi, 
It seems that this bug is not caused by the SDK. I was not able to reproduce the problem on my device. Could you please update to the latest SDK and try again? 

I'm closing this issue now. Please feel free to reopen if the problem persists.

**Closed by Amazon-tianrenz** 2017-11-01 23:39 UTC
