### ISSUE TITLE
Alexa audio player with question directive afterwards

### ISSUE THREAD

**Issue by kevinwu** [alexa/alexa-skills-kit-sdk-for-nodejs#132] opened 2017-06-14 13:36 UTC
Hi,

currently, if I have something like this:
`this.response.speak("hello").audioPlayerPlay("REPLACE_ALL", url, "1", null, 0).listen("world");`
then Alexa will first say "hello", after the usual while say "world" and only then after an awkward silence play the audio.

On the other hand if we have this:
`this.response.speak("hello").audioPlayerPlay("REPLACE_ALL", url, "1", null, 0);`
then Alexa will say "hello", immediately play the audio file and then end the session.

Is it possible to have Alexa say "hello", immediately play the audio file and then say/ask "world"?
What might be a possible workaround to make this happen?

**Comment by rszarek** [comment] 2017-06-14 14:33
Kevin I have never wrote a program and this is my first attempt. I'm not really sure how to lay everything out. There is only one really informative response that I had found. The question would be, Alexa, what is ( the meaning of, where is the expression from, does it mean, when was the term from,)420? The questions and all related can be answered on a wed site on Huffington. I am really asking for a mentor to help walk me through step by step, I have read the information but of course o am very unsure of myself. Would you be willing to assist me in this? I appreciate your help. Than you Rhonda

**Comment by odintsovamz** [comment] 2017-06-14 16:33
Kevin, the described use case is not by design of audio player support. With audio player targeting long audio files and play lists skill have to end and exit session to return context back to alexa to be able to respond to user in other ways. If your audio is short enough (under 90 seconds) you can just use <audio> tag in ssml (see https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/speech-synthesis-markup-language-ssml-reference#audio )

**Comment by Amazon-tianrenz** [comment] 2017-10-31 19:48
Hi, I'm closing this issue for now. Please feel free to reopen if further questions appear

**Closed by Amazon-tianrenz** 2017-10-31 19:48 UTC
