### ISSUE TITLE
S3 delete persistent attributes not working

### ISSUE THREAD

**Issue by harristom** [alexa/alexa-skills-kit-sdk-for-nodejs#558] opened 2019-05-30 19:54 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

I set/save some persistent attributes, then delete them

## Current Behavior

Could not delete item (x) from bucket (y): Access Denied

## Steps to Reproduce (for bugs)

Skill is Alexa Hosted Skill and attributes are successfully saved after using instructions [here](https://developer.amazon.com/docs/hosted-skills/build-a-skill-end-to-end-using-an-alexa-hosted-skill.html#persistence).

Trying to delete with:
```
const attributesManager = handlerInput.attributesManager;
 await attributesManager.deletePersistentAttributes();
```
Results in the error above

## Your Environment

    "ask-sdk-core": "^2.0.7",
    "ask-sdk-model": "^1.4.1",
    "aws-sdk": "^2.326.0",
    "ask-sdk-s3-persistence-adapter": "^2.0.0",
Alexa hosted skill

**Comment by hideokamoto** [comment] 2019-05-30 23:36
The `deleteAttributes()` method is available in grater than 2.4.0.
You should replace your package.json like this.


```
"ask-sdk-core": "^2.6.0",
"ask-sdk-model": "^1.16.0",
"aws-sdk": "^2.326.0",
"ask-sdk-s3-persistence-adapter": "^2.6.0",
```

**Comment by harristom** [comment] 2019-05-31 09:17
Tried that but still getting the same error. The method definitely exists
because the error I get is that I don't have access to the item in S3.

**Comment by hideokamoto** [comment] 2019-06-10 05:31
Well...
Is the item not empty?
Probably, some S3 API throws `Access Denied` error when the item not found in the S3 bucket.

Could you run the following code to reproduce the issue?

## First test
The code will create an S3 object before deleting the object.
So It will work well.

```typescript
    const attributesManager = handlerInput.attributesManager;
    attributesManager.setPersistentAttributes({
      test: 'hello'
    })
    await attributesManager.savePersistentAttributes()
    await attributesManager.deletePersistentAttributes();
```

## Second test

The example will throw an Error from `getPersistentAttributes` method.
Because the user's S3 object is already deleted.

``` typescript
  const attributesManager = handlerInput.attributesManager;
  attributesManager.setPersistentAttributes({
      test: 'hello'
    })
  await attributesManager.savePersistentAttributes()
  await attributesManager.deletePersistentAttributes();
  try {
    const item =await attributesManager.getPersistentAttributes()
    console.log('Complete')
  } catch (e) {
   console.log(e)
   console.log('actual')
  } 
```

## I think
We should use `try ~ catch` to run the `deletePersistentAttributes()` method.
Because sometime the S3 object is not found.

```typescript
  try {
    await attributesManager.deletePersistentAttributes()
  } catch (e) {
   console.log(e)
  } 
```

**Comment by franklin-lobb** [comment] 2019-06-10 14:46
I tried this and found the function through the error when using Hosted Skills, and did not throw an error if the function was running in my own AWS account.

**Comment by hideokamoto** [comment] 2019-06-11 03:33
How do you create the adaptor?
In Hosted skill, we need to set the `process.env.S3_PERSISTENCE_BUCKET` param to bucketName.

```typescript
Alexa.SkillBuilders.custom()
  .withPersistenceAdapter(
    new persistenceAdapter.S3PersistenceAdapter({
       bucketName: process.env.S3_PERSISTENCE_BUCKET
    })
  )
```

**Comment by franklin-lobb** [comment] 2019-06-11 05:28
Within the Alexa-hosted environment, you set `bucketName` to the S3_PERSISTENCE_BUCKET value which is set by the Alexa-hosted environment to your S3 bucket name.  To create the adapter outside of the Alexa-hosted environment, set `bucketName` to the name of the bucket you want to store the data in (ensuring the function execution role has appropriate access to the bucket).

**Comment by ShenChen93** [comment] 2019-06-11 22:57
Hi @harristom @franklin-lobb ,

Thanks for reporting this bug. I reproduced the error you mentioned, but it's not our sdk side problem. Therefore, I need to reach out to host skill team to figure it out. Will inform you once I got their response.

Thanks,
Shen

**Comment by ShenChen93** [comment] 2019-06-11 23:28
The service team started their work on this issue. Will update here once they fixed it.

**Comment by ShenChen93** [comment] 2019-06-19 18:28
@harristom @franklin-lobb 

I think this issue has been fixed already. Could you please try and see if the problem still exist ?

Thanks,
Shen

**Comment by ShenChen93** [comment] 2019-06-20 17:58
Close it for now, please feel free to reopen it if the problem still exist.

**Closed as completed by ShenChen93** 2019-06-20 17:58 UTC
Labels: bug
