### ISSUE TITLE
i'm making a simple application and i getting this error {"errorMessage":"Requested resource not found"} I created a terable 

### ISSUE THREAD

**Issue by dante-byte** [alexa/alexa-skills-kit-sdk-for-nodejs#664] opened 2020-11-14 13:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Other... Please describe: i have a simple node.js crud app i make a post request to a table that i created in dynamodb adn i get and error {"errorMessage":"Requested resource not found"} 500 I read the documentation and it says to try it again and it still didn't work 
</code></pre>

 i have a simple node.js crud app i make a post request to a table that i created in dynamodb adn i get and error {"errorMessage":"Requested resource not found"} 500 I read the documentation and it says to try it again and it still didn't work 

## Expected Behavior

 i have a simple node.js crud app i make a post request to a table that i created in dynamodb adn i get and error {"errorMessage":"Requested resource not found"} 500 I read the documentation and it says to try it again and it still didn't work 

## Possible Solution

 i have a simple node.js crud app i make a post request to a table that i created in dynamodb adn i get and error {"errorMessage":"Requested resource not found"} 500 I read the documentation and it says to try it again and it still didn't work 

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by ShenChen93** [comment] 2020-11-16 05:24
Hi @dante-byte ,

Could you please provide more detailed info thus I could try to reproduce the issue. I wonder if you are making a Alexa Skill with the ask-sdk-dynamodb-persistence-adapter ? And which instruction are you following ? Also is your skill an Alexa hosted skill or non-hosted skill ?

Thanks,
Shen

**Comment by ShenChen93** [comment] 2020-12-01 21:10
Close this issue for now since no responding. Please feel free to reopen :)

**Closed as completed by ShenChen93** 2020-12-01 21:10 UTC
