### ISSUE TITLE
Error on SMAPI Call "ListInteractionModelCatalogVersions"

### ISSUE THREAD

**Issue by StefanV85** [alexa/alexa-skills-kit-sdk-for-nodejs#693] opened 2021-07-10 20:16 UTC
## I'm submitting

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I have Problem when requesting the versions of my slot-catalog.
Everything works fine, before i had 50 versions.
Now i can't reqeust the list with pagination.

The Problem occurs in the "ask-cli", and in the "ask-smapi-sdk".
Because i think it's related to the smapi endpoint, i decided to create an issue here. if this is the wrong place for the smapi team, please let me know.

It works when i call: 
ask smapi list-interaction-model-catalog-versions --catalog-id amzn1.ask.interactionModel.catalog.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

The System list 50 Versions and the next token
e.g:  "nextToken": "50|1625914867177",

If i add the next token parameter i get an error: 
ask smapi list-interaction-model-catalog-versions --catalog-id amzn1.ask.interactionModel.catalog.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --next-token "50|1625914867177"

Errors: 
"message": "Server cannot process the request due to a client error e.g. the catalog definition is invalid."
and
"message": "request uri is malformed."

The error describes a problem with the catalog definition, but the catalog worked well before i had > 50 versions.
And highest Version (51) was created correctly, because i can request this version via: 
ask smapi get-interaction-model-catalog-version --catalog-id amzn1.ask.interactionModel.catalog.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx --vers 51

The exact same problem i get when calling: smapiClient.callListInteractionModelCatalogVersionsV1 in the "ask-smapi-sdk"

## Expected Behavior
The smapi should return my slot-catalog-versions considerring the pagination.

## Current Behavior
"message": "Server cannot process the request due to a client error e.g. the catalog definition is invalid."
and
"message": "request uri is malformed."

## Your Environment
Error occurs in ask-cli version 2.22.4 and in the ask-smapi-sdk version 1.3.0.
Operating System Windows 10

## Node.js and NPM Info
NodeJS Version v14.15.5
NPM Version: 6.14.11

Kind Regarads
Stefan

**Comment by ShenChen93** [comment] 2021-07-10 22:48
Hi @StefanV85 ,

Thanks for reporting this issue. I tried the same smapi command with --debug option, and i got the following payload:
```
{
  "catalogId": "amzn1.ask.interactionModel.catalog.xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
  "maxResults": null,
  "nextToken": "50|1625914867177",
  "sortDirection": null,
  "sortField": null
}
```

Seems the nextToken is correctly added into the payload. I will reach out to service team to figure it out why this payload is not valid next Monday.  Could you provide your skill ID thus we could check the log ?

Thanks,
Shen

**Comment by StefanV85** [comment] 2021-07-10 23:26
Hi Shen,
Thank you very much for your support. 
My Skill-ID is the following: amzn1.ask.skill.fcceb23a-ada9-448e-b788-7ec921dadcea

Kind Regards
Stefan

**Comment by ShenChen93** [comment] 2021-08-26 20:40
Hi @StefanV85 ,

Thanks for your patient. The fix for this issue is done by our service team today, could you please check if the issue is still exist on your side ?

Thanks,
Shen

**Closed as completed** 2021-10-04 20:52 UTC
Labels: response needed
