### ISSUE TITLE
:askWithCard crashes

### ISSUE THREAD

**Issue by Sketusky** [alexa/alexa-skills-kit-sdk-for-nodejs#166] opened 2017-08-11 12:21 UTC
When I use `:askWithCard`, skill works correctly only with Amazon Device, when trying to use it on Android app it doesn't.

I've solved the problem on Android when I switched to simple `:ask` but still I can't send cards.

The problem occurred yesterday, before Thursday everything was working with cards.

**Comment by ysak-y** [comment] 2017-08-29 15:36
Do you have any error message? Does Android IDE print any logs?

**Comment by bclement-amazon** [comment] 2017-09-01 18:58
How are you invoking your skill on Android?

**Comment by shrobon** [comment] 2017-09-30 08:04
I am facing the same issue. 
tellWithCards works fine , but askWithCards does not work.

**Comment by shrobon** [comment] 2017-09-30 20:34
Thanks @bclement-amazon ! 👍 
I got it to work 🥇

**Comment by Amazon-tianrenz** [comment] 2017-10-31 23:19
Close this as the issue is resolved. Please feel free to reopen if further problems appear

**Closed by Amazon-tianrenz** 2017-10-31 23:19 UTC
Labels: Awaiting reply
