### ISSUE TITLE
Multi-turn SMAPI interactions not possible

### ISSUE THREAD

**Issue by garejon** [alexa/alexa-skills-kit-sdk-for-nodejs#669] opened 2020-12-10 13:30 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Multi-turn for SMAPI SDK:
Currently a request to an Alexa skill can be simulated, but it is not possible to simulate two requests that are part of the same skill usage. For example, say I am listening to a some music, and want to say 'next' to go to the next song, SMAPI will act as if 'next' is being said as part of a different session. As if you've closed the skill, and then said 'ask [skill name] for next' or just 'next'. 

## Current Behavior

Each request sent to the skill via SMAPI acts as if the skill has been closed and is being reopened, instead of a continuous session, where the token sent to the Alexa skill would be preserved between calls.

## Steps to Reproduce (for bugs)

This is in reference to using the following class and its functions:
const smapiClient = new Alexa.StandardSmapiClientBuilder()
smapiClient.simulateSkillV2()
smapiClient.getSkillSimulationV2()

## Context

Without this capability, comprehensive end-to-end testing is not possible.

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development: 14
* NPM version used for development: 6

**Comment by ShenChen93** [comment] 2020-12-10 20:33
Hi @garejon 

Thanks for posting this issue. If you are using the smapiClient.simulateSkillV2(), it should be able to keep the session open. Our VSCode extension also [use this api to achieve the skill simulator feature](https://github.com/alexa/ask-toolkit-for-vscode/blob/development/src/utils/simulateSkillHelper.ts#L114) and it support multi-turn dialog. This is the smapi api behind the simulateSkillV2 function: [ref](https://developer.amazon.com/en-US/docs/alexa/smapi/skill-simulation-api.html#skill-simulation-api-request). As it mentioned, developer could keep the session open  by setting `session.mode = 'DEFAULT'`.  

Thus, when you use the simulateSkillV2 function, could you please try to set the session property such as [here](https://github.com/alexa/ask-toolkit-for-vscode/blob/development/src/utils/simulateSkillHelper.ts#L109),  and see if the issue still exist ?

Thanks,
Shen

**Comment by leotorres-16** [comment] 2020-12-14 09:39
Hi @ShenChen-Amazon,

I am working on the same project with @garejon I can confirm we are using the `DEFAULT` session mode, however our skill relies heavily on the Audio Player, could this be the reason why we can't do multi turn interactions ? We are trying to tests a simple play -> pause -> resume scenario and when we try to `pause` or go `next` for example with the simulator, the session is gone and the commands are not recognised.

Thanks a lot for your quick response.

**Comment by ShenChen93** [comment] 2020-12-15 01:26
@leotorres-16 @garejon ,

Thanks for the confirmation. I reached out to service team asking if this API support audioPlayer use case, the answer is unfortunately this simulate api right now doesn't support this use case. When the simulate api is invoked, it will auto register device for testing the skill.  However, the auto registered device so far doesn't have certain capabilities like player/timer/alarms. Thus, you may need to use a real Alexa device for testing the skill for now.

Sorry for the inconvenience. I think it's a really good feature request to the service side. Would be great if you guys could log this feature request at [Alexa Forums](https://forums.developer.amazon.com/) and vote for it.  I will close the issue on SDK side, please feel free to reopen if you have any questions :)

Thanks,
Shen

**Closed as completed by ShenChen93** 2020-12-15 01:26 UTC
