### ISSUE TITLE
Alexa hosted skill DynamoDB permission error

### ISSUE THREAD

**Issue by matijagrcic** [alexa/alexa-skills-kit-sdk-for-nodejs#711] opened 2022-03-04 09:53 UTC
Hi,

I have a Alexa Hosted Skill which is live and published. Wanted to continue development on it recently
but since the upgrade to DynamoDB Console v2 I can't explore the items getting  the following error message

```
We couldn't load your item. Contact your account administrator to request the necessary permissions.
User: arn:aws:sts::XXXXXXXXXX:assumed-role/VoiceHubSSORole/VoiceHubSSORole is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:XXXXXXXXXX:table/XXXXXXXXXX-XXXXXXXXXX
```

If I can create a new Alexa hosted skill I get the same error message. I can add new items in the DynamoDB thru the Console but exploring them gives this error message even though my account is the Administrator and this worked previously just fine.

Do you have any pointers on what might cause this? Or to whom can I direct this issue to? I've opened tickets for Alexa support but it's been over a week now without any response.

**Comment by tkm22** [comment] 2022-03-08 05:00
Can you Try this again, we have changed some S3 access policy last week, but revert back right now, this might be related to your problem.

**Comment by matijagrcic** [comment] 2022-03-08 10:57
Thanks for responding @tkm22. I've tried and the error is the same. Even when I create a new Alexa Hosted skill I can't explore items in DynamoDB Console. Can you please look into this?

**Comment by tkm22** [comment] 2022-03-09 01:43
Could you provide me the AWS account, where the DynamoDB is in?

**Comment by tkm22** [comment] 2022-03-09 01:52
And when you refer DynamoDB Console, can you give me the exact link?

**Comment by matijagrcic** [comment] 2022-03-09 10:10
Sure, go to 

1. Alexa Console https://developer.amazon.com/alexa/console/ask
2. Create a Custom Alexa Hosted Skill https://developer.amazon.com/alexa/console/ask/create-new-skill
3. Then go to the Code tab of the skill https://developer.amazon.com/alexa/console/ask/editor/amzn1.ask.skill.d2a00082-eee3-4161-9390-182a5b7c14e8/development/en_GB
4. Then click on the DynamoDB icon and try and open any of the item in the table https://us-east-1.console.aws.amazon.com/dynamodbv2/home?region=us-east-1#item-explorer?initialTagKey=&table=d2a00082-eee3-4161-9390-182a5b7c14e8
5. You'll get the following
> We couldn't load your item. Contact your account administrator to request the necessary permissions.
> User: arn:aws:sts::XXXXXXXXXX:assumed-role/VoiceHubSSORole/VoiceHubSSORole is not authorized to perform: dynamodb:GetItem on resource: arn:aws:dynamodb:us-east-1:XXXXXXXXXX:table/XXXXXXXXXX-XXXXXXXXXX

I didn't masked the links above so you can easily debug if you want, it's just a new Alexa hosted skill I created to verify it's not only happening on the already live and published skill.

**Comment by matijagrcic** [comment] 2022-03-14 14:10
Hey @tkm22 any chance you were available to look at this?

**Comment by tkm22** [comment] 2022-03-14 17:30
Hey @matijagrcic , now we understand the issue is not under our team control (SDK), which is related to the team that takes care of role permission on VoiceHubSSORole as you can tell from the error, I have followed up with their team last week and they said they had acknowledged the issue and prioritized to work on that. I will give an update here when they solve the issue.

**Comment by matijagrcic** [comment] 2022-03-15 11:47
Thanks @tkm22, that's great to hear. Looking forward to your update when it's resolved.

**Comment by matijagrcic** [comment] 2022-03-25 11:52
Hey @tkm22  is there any info available when to expect this fixed?

**Comment by tkm22** [comment] 2022-03-25 17:41
Hey @[matijagrcic](https://github.com/matijagrcic), sorry to keep you waiting. In short, it is not fixed but I see their team has planned on this issue 3 days ago. 

Since I am not on their team, I couldn't tell when it will be fixed, but I assume they are going to work on this recently since it is on their active sprint plan (I don't have access to it), but someone also told me before it will require plenty of time to fix.

**Comment by tkm22** [comment] 2022-04-19 04:19
closing this, since from internal ticket status, it's been resolved. You can double check the getitem permission.

**Closed as completed by tkm22** 2022-04-19 04:19 UTC

**Comment by matijagrcic** [comment] 2022-04-20 19:45
Thanks @tkm22  that's fixed now, just verified.

**Comment by gprasanthi9** [comment] 2025-04-24 22:03
Hi ,i'm clicking from the ASK dynamodb table saved data but for me its getting similar error which is highlighted .

User: arn:aws:sts::515966536933:assumed-role/VoiceHubSSORole/VoiceHubSSORole is not authorized to perform: application-autoscaling:DescribeScalingActivities on resource: arn:aws:application-autoscaling:us-east-1:515966536933:scalable-target/* because no identity-based policy allows the application-autoscaling:DescribeScalingActivities action

could anyone help in this please
