### ISSUE TITLE
ISP customProductPrompts Inconsistency

### ISSUE THREAD

**Issue by DecathectZero** [alexa/alexa-skills-kit-sdk-for-nodejs#655] opened 2020-09-20 15:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

In `ask-smapi-model` for `CustomProductPrompts` it is referred to as `boughtConfirmationPrompt`
https://github.com/alexa/alexa-apis-for-nodejs/blob/master/ask-smapi-model/index.ts#L902

but as defined in this schema https://developer.amazon.com/en-US/docs/alexa/smapi/isp-schemas.html it is referred to as `boughtCardDescription` - this inconsistency is a bit annoying and is it intended?

This causes an error when making a `smapi.updateIspForProductV1` or `createIspForVendorV1` call and requires the type to be overridden

**Comment by ShenChen93** [comment] 2020-09-22 00:13
Hi @DecathectZero ,

Thanks for reporting this issue. Idealy those two schema should be exactly match, I will reachout to service team and figure out whether we need to update our model to use property name `boughtCardDescription`. If it's a model issue, we will fix it in next model release.

Thanks,
Shen

**Comment by ShenChen93** [comment] 2020-09-24 17:38
Hi @DecathectZero ,

We released a new patch version of SMAPI Model 1.12.2 yesterday which fix this SPI issue. Thus will close this issue for now. Could you please download the latest SMAPI model and see if the issue is fixed. Please feel free to reopen if you still have questions or converns.

Thanks,
Shen

**Closed as completed by ShenChen93** 2020-09-24 17:38 UTC
Labels: investigating
