### ISSUE TITLE
ListManagementService isn't accepting the apiAccessToken anymore

### ISSUE THREAD

**Issue by TimeO84** [alexa/alexa-skills-kit-sdk-for-nodejs#683] opened 2021-02-23 10:50 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

ListManagementService isn't acception the apiAccessToken anymore, you have to use the deprecated consentToken

## Expected Behavior
let ListManagementService = handlerInput.serviceClientFactory.getListManagementServiceClient();
let listresp =await ListManagementService.getListsMetadata();

## Current Behavior
```
let ListManagementService = handlerInput.serviceClientFactory.getListManagementServiceClient();
let listresp =await ListManagementService.getListsMetadata(); 
```
Above Code throws this exception:

2021-02-23T10:00:50.240Z	db1b9afc-2542-433d-8b92-a92135c8f04e	INFO	getListsMetadata Ex Error [ServiceError]: Forbidden
    at ListManagementServiceClient.<anonymous> (/var/task/node_modules/ask-sdk-model/index.js:219:35)
    at step (/var/task/node_modules/ask-sdk-model/index.js:45:23)
    at Object.next (/var/task/node_modules/ask-sdk-model/index.js:26:53)
    at fulfilled (/var/task/node_modules/ask-sdk-model/index.js:17:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  statusCode: 403,
  response: { Message: 'Request is not authorized.' }
}

## Possible Solution
```
let ListManagementService = handlerInput.serviceClientFactory.getListManagementServiceClient();
ListManagementService.apiConfiguration.authorizationValue = handlerInput.requestEnvelope.session.user.permissions.consentToken;
let listresp =await ListManagementService.getListsMetadata();

```
## Steps to Reproduce (for bugs)
```
let ListManagementService = handlerInput.serviceClientFactory.getListManagementServiceClient();
let listresp =await ListManagementService.getListsMetadata();
```

## Context

My Skill stopped working until i found the described Workaround
## Your Environment

* ASK SDK for Node.js used: ask-sdk-core/2.10.1
* Operating System and version: AWS Lambda Node.js 12.x

## Node.js and NPM Info
* Node.js version used for development: AWS Lambda Node.js 12.x
* NPM version used for development: npm@3.10.10

**Comment by ShenChen93** [comment] 2021-02-23 23:27
Hi @TimeO84 ,

Thanks for using our SDK ! For this issue, I wonder if you correctly grant permission to the skills, here is the doc for instruction: https://developer.amazon.com/en-US/docs/alexa/custom-skills/access-the-alexa-shopping-and-to-do-lists.html#integrate-list-management-capabilities-into-your-skill.

Basically, you would need to first go to developer console, at the permission tab, you need to config that the skill may need read / write list:
![image](https://user-images.githubusercontent.com/45435608/108921369-154c0500-75eb-11eb-9b02-324da9e18982.png)

Second, go to your Alexa App, find the skills & games list and find the skill you are developing. If you finished the fist step, you will see the `setting` button, go to setting and grant permission to the skill. 

I am able to get the list after I finished above two steps. Let me know if it works for you :)

Thanks,
Shen

**Comment by TimeO84** [comment] 2021-02-24 00:04
Hello Shen,

all my permissions are set correctly. It stopped working for about 2 weeks. If i use the given consentToken I am able to retrieve the Lists Metadata. Maybe i am wrong on GitHub with this Problem and it is a Problem with the Service itself.

**Comment by ShenChen93** [comment] 2021-02-24 00:31
Hi @TimeO84 ,

Umm, if so probably we can't help you investigate the root cause. I would recommend you to log this issue to [Alexa Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html), thus people from service team could works with you to figure it out.

Closing this ticket from sdk side for now. Please feel free to reopen if you have any other concerns :)

Thanks,
Shen

**Closed as completed by ShenChen93** 2021-02-24 00:31 UTC

**Comment by ShenChen93** [comment] 2021-02-24 00:42
@TimeO84 

Actually Alexa just set up a 3P slack community: http://alexa.design/slack. Maybe you could also log question there ?
