### ISSUE TITLE
No speech after :tellWithLinkAccountCard

### ISSUE THREAD

**Issue by ChrisSchneider** [alexa/alexa-skills-kit-sdk-for-nodejs#172] opened 2017-08-22 08:28 UTC
I'm fighting with an issue where an Alexa skill requires account linking, but the user skips this and then interacts with the skill. As the account is not linked, I emit `:tellWithLinkAccountCard` as documented by Amazon. However, the text is not spoken by Alexa. This issue is incredible frustrating to me, as the skill was repeatedly rejected by Amazon because of this bug!

Code:
```js
this.emit(':tellWithLinkAccountCard', 'Please link your account to use this skill properly')
```

Response returned to Alexa by skills kit SDK:
```js
{ version: '1.0',
  response: 
   { shouldEndSession: true,
     outputSpeech: 
      { type: 'SSML',
        ssml: '<speak> Please link your account to use this skill properly </speak>' },
     card: { type: 'LinkAccount' } },
  sessionAttributes: { ... }
}
```

Response shown in Service Simulator:
```js
{
  "version": "1.0",
  "response": {
    "card": {},
    "speechletResponse": {
      "card": {},
      "shouldEndSession": true
    }
  },
  "sessionAttributes": { ... }
}
```

I'm using the latest skills kit SDK.

**Comment by bclement-amazon** [comment] 2017-09-01 18:24
Hey @ChrisSchneider, Have you tested this on a device? It appears to be working just fine!

I get the speach "Please link your account to use this skill properly"

**Comment by bclement-amazon** [comment] 2017-09-05 15:20
Closing as i'm not able to reproduce.

**Closed by bclement-amazon** 2017-09-05 15:20 UTC
Labels: Awaiting reply

**Comment by ChrisSchneider** [comment] 2017-09-05 15:24
Sorry for the late response, I was out of office the last couple of days.
It seems to be fixed now, I cannot reproduce the issue either.

**Comment by bclement-amazon** [comment] 2017-09-05 15:26
Great to hear! @ChrisSchneider 👍  Wish you the best through the cert process!
